subdir-m += fid
subdir-m += obdclass
subdir-m += ptlrpc
subdir-m += obdecho
subdir-m += mgc

subdir-m += ost mgs mdt mdd ofd quota osp lod lfsck
subdir-m += lov osc mdc lmv llite fld
subdir-m += osd-ldiskfs
#subdir-m += osd-zfs


include /home/build/lustre-release/Rules
